### ISSUE TITLE
HI question about the pvtu and the vtu with MPI in using VTK package

### ISSUE THREAD

**Issue by xigetongkuaizao** [kursatyurt/kursatyurt#1]
Ｉ　ｃａｎ　ｗｒｉｔｅ　ｔｈｅ　（＿０　＿１　＿２　＿３）　．ｖｔｕ，ｂｕｔ　ｃａｎｎｏｔ　ｗｒｉｔｅ　ｔｈｅ　．ｐｖｔｕ　　ｃａｎ　ｙｏｕ　ｇｉｖｅ　ｓｏｍｅ　ｈｅｌｐ？　ｔｈａｎｋｓ．
ｃｏｄｅ：
    int mpi_size, mpi_rank;　
    MPI_Comm comm = MPI_COMM_WORLD;
    MPI_Info info = MPI_INFO_NULL;
    MPI_Init(&argc, &argv);
    MPI_Comm_size(comm, &mpi_size);
    MPI_Comm_rank(comm, &mpi_rank);

    cout<<"this is the rank:" << mpi_rank<<"===of the size:" << mpi_size << endl;

    vtkNew<vtkXMLUnstructuredGridWriter> writer;

    vtkNew<vtkPoints> points;
    points->InsertNextPoint(0, 0, 0 + mpi_rank);
    points->InsertNextPoint(1, 0, 0 + mpi_rank);
    points->InsertNextPoint(1, 1, 0 + mpi_rank);
    points->InsertNextPoint(0, 1, 1 + mpi_rank);

    vtkNew<vtkTetra> tetra;

    tetra->GetPointIds()->SetId(0, 0);
    tetra->GetPointIds()->SetId(1, 1);
    tetra->GetPointIds()->SetId(2, 2);
    tetra->GetPointIds()->SetId(3, 3);

    vtkNew<vtkCellArray> cellArray;
    cellArray->InsertNextCell(tetra);

    vtkNew<vtkUnstructuredGrid> unstructuredGrid;
    unstructuredGrid->SetPoints(points);
    unstructuredGrid->SetCells(VTK_TETRA, cellArray);

    vtkSmartPointer<vtkDoubleArray> vectorE = vtkSmartPointer<vtkDoubleArray>::New();
    vectorE->SetName("elemScale");
    vectorE->SetNumberOfValues(1);
    vectorE->SetValue(0, 1.1 + mpi_rank);

    if (mpi_rank == 0) {
        writer->SetFileName("Voxel_0.vtu");
    }
    if (mpi_rank == 1) {
        writer->SetFileName("Voxel_1.vtu");
    }
    if (mpi_rank == 2) {
        writer->SetFileName("Voxel_2.vtu");
    }
    if (mpi_rank == 3) {
        writer->SetFileName("Voxel_3.vtu");
    }

    unstructuredGrid->GetCellData()->SetScalars(vectorE);

    writer->SetInputData(unstructuredGrid);

    writer->Write();

ｉｎ　ｕｓｉｎｇ　ｔｈｉｓ　ｃａｎｎｏｔ　ｇｅｔ　ｔｈｅ　ｐｖｔｕ
    if (mpi_rank == 0) 
    {
        //vtkSmartPointer<vtkXMLPUnstructuredGridWriter> pwriter;
        auto pwriter = vtkSmartPointer<vtkXMLPUnstructuredGridWriter>::New();
        //vtkSmartPointer pwriter = vtkSmartPointer::New();
       // pwriter->EncodeAppendedDataOff();
        
        pwriter->SetFileName("Voxel.pvtu");
        pwriter->SetNumberOfPieces(mpi_size);
        pwriter->SetStartPiece(0);
        pwriter->SetEndPiece(3);

        pwriter->SetInputData(unstructuredGrid);

        //pwriter->Write();
        pwriter->Update();
     

    }

**Comment by kursatyurt** [comment]
This is not a forum. Don't spam people!
